"""Drop Asset, create UserPreferences

Revision ID: 52f6c080ff3a
Revises: dc7e4f592106
Create Date: 2024-05-23 21:14:46.829448

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52f6c080ff3a"
down_revision = "dc7e4f592106"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("strategy_display_option", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "transaction", sa.Column("portfolio_id", sa.Integer(), nullable=False)
    )
    op.add_column("transaction", sa.Column("ticker", sa.String(), nullable=False))
    op.add_column(
        "transaction", sa.Column("purchased_at", sa.DateTime(), nullable=False)
    )
    op.drop_constraint("transaction_asset_id_fkey", "transaction", type_="foreignkey")
    op.create_foreign_key(None, "transaction", "portfolio", ["portfolio_id"], ["id"])
    op.drop_column("transaction", "asset_id")
    op.drop_table("asset")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("portfolio_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("symbol", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"], ["portfolio.id"], name="asset_portfolio_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="asset_pkey"),
    )
    op.add_column(
        "transaction",
        sa.Column("asset_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "transaction", type_="foreignkey")
    op.create_foreign_key(
        "transaction_asset_id_fkey",
        "transaction",
        "asset",
        ["asset_id"],
        ["id"],
    )
    op.drop_column("transaction", "purchased_at")
    op.drop_column("transaction", "ticker")
    op.drop_column("transaction", "portfolio_id")
    op.drop_table("user_preferences")
    # ### end Alembic commands ###
