"""Add user_id to Transaction

Revision ID: 630e33df71a0
Revises: bb57a93323ac
Create Date: 2024-05-23 21:43:58.262558

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "630e33df71a0"
down_revision = "bb57a93323ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "transaction", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transaction", type_="foreignkey")
    op.drop_column("transaction", "user_id")
    # ### end Alembic commands ###
