"""Make User <-> UserPreferences 1to1

Revision ID: 6a9272300ccd
Revises: f04ba62bcfe2
Create Date: 2024-05-28 11:40:46.968314

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "6a9272300ccd"
down_revision = "f04ba62bcfe2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user_preferences", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_preferences", type_="unique")
    # ### end Alembic commands ###
