"""Fix user_preferences types

Revision ID: 99be8da37129
Revises: 6a9272300ccd
Create Date: 2024-05-28 11:45:00.408005

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "99be8da37129"
down_revision = "6a9272300ccd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_preferences",
        "strategy_display_option",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using="strategy_display_option::integer",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_preferences",
        "strategy_display_option",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        postgresql_using="strategy_display_option::varchar",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
