"""Make transaction quantity a float, price -> price_cents

Revision ID: a068cdb05725
Revises: b6791d9b45d7
Create Date: 2024-06-01 16:46:29.445659

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a068cdb05725"
down_revision = "b6791d9b45d7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("price_cents", sa.Integer(), nullable=True))
    op.execute("UPDATE transaction SET price_cents = price * 100")
    op.alter_column("transaction", "price_cents", nullable=False)
    op.drop_column("transaction", "price")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("price", sa.Integer(), nullable=True))
    op.execute("UPDATE transaction SET price = price_cents / 100")
    op.alter_column("transaction", "price", nullable=False)
    op.drop_column("transaction", "price_cents")
    # ### end Alembic commands ###
