"""Cascade on user delete

Revision ID: a8d66f65acf5
Revises: 630e33df71a0
Create Date: 2024-05-25 08:42:44.584652

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "a8d66f65acf5"
down_revision = "630e33df71a0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "transaction_portfolio_id_fkey", "transaction", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "transaction_portfolio_id_fkey",
        "transaction",
        "portfolio",
        ["portfolio_id"],
        ["id"],
    )
    # ### end Alembic commands ###
