"""Add preferences to User

Revision ID: bb57a93323ac
Revises: 52f6c080ff3a
Create Date: 2024-05-23 21:40:02.047494

"""

# revision identifiers, used by Alembic.
revision = "bb57a93323ac"
down_revision = "52f6c080ff3a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
