"""Use int for strategy display option

Revision ID: f04ba62bcfe2
Revises: a8d66f65acf5
Create Date: 2024-05-25 09:09:38.244172

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "f04ba62bcfe2"
down_revision = "a8d66f65acf5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "transaction", "portfolio", ["portfolio_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transaction", type_="foreignkey")
    # ### end Alembic commands ###
