"""Add IndexPriceHistory

Revision ID: f7c14981fd35
Revises: a068cdb05725
Create Date: 2024-06-02 20:25:41.548341

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7c14981fd35"
down_revision = "a068cdb05725"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "index_price_history",
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("open_price_cents", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("date", "ticker", name="pk_date_ticker"),
    )
    op.create_index(
        "idx_index_price_history_date", "index_price_history", ["date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_index_price_history_date", table_name="index_price_history")
    op.drop_table("index_price_history")
    # ### end Alembic commands ###
