"""Cascade Delete Transactions

Revision ID: fcede586204b
Revises: f7c14981fd35
Create Date: 2024-06-18 11:06:50.176623

"""

# revision identifiers, used by Alembic.
revision = "fcede586204b"
down_revision = "f7c14981fd35"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
