name: Docker Image CI

on:
  merge:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.0"

      - name: Build the Docker image
        run: cd deploy && docker compose build
